apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafka.clusterName }}-entity-operator
  namespace: {{ .Values.resources.namespace }}
  labels:
    app: strimzi
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
imagePullSecrets:
- name: {{ .Values.image.secretName }}


