resources:
  namespace: kafka
hooks:
  customresources: crd-install
  firstinstallPriority: pre-install
  firstupgradePriority: pre-upgrade
  lastinstallPriority: post-install
  lastupgradePriority: post-upgrade
image:
  secretName: icr-secret
  registry: us.icr.io
  username: iamapikey
  password: mUN5OKR0tHLf7LgiFHtLZ8nh8XamXnJ7_IS46j0yb1cl
operator:
  image:
    repository: strimzi/operator
    tag: 0.16.2
    pullPolicy: IfNotPresent
kafka:
  clusterName: my-cluster
  version: 2.4.0
  logVersion: 2.4
  replicas: 3
  clientAuthType: tls
  sslExpose: true
  exposeType: loadbalancer
  aclAuthType: simple
  image:
    repository: us.icr.io/msil_gen2_connect_dev/kafka-cluster
    tag: 0.16.2
  storageType: persistent-claim
  storageSize: 20Gi
  claimDeletePolicy: false
  storageClass: ibmc-file-retain-gold
  userName: my-user
zookeeper:
  replicas: 2
  storageType: persistent-claim
  storageSize: 20Gi
  claimDeletePolicy: false
  storageClass: ibmc-file-retain-gold
 


