resources:
  namespace: kafka
hooks:
  customresources: crd-install
  firstinstallPriority: pre-install
  firstupgradePriority: pre-upgrade
  lastinstallPriority: post-install
  lastupgradePriority: post-upgrade
image:
  secretName: dockerhub
  registry: index.docker.io/v1
  username: avashkumar
  password: Reduced@0
operator:
  image:
    repository: avashkumar/kafka-operator
    tag: 0.16.2
    pullPolicy: IfNotPresent
kafka:
  clusterName: my-cluster
  version: 2.4.0
  logVersion: 2.4
  replicas: 3
  clientAuthType: tls
  sslExpose: true
  exposeType: loadbalancer
  aclAuthType: simple
  image:
    repository: avashkumar/kafka
    tag: 0.16.2
  storageType: persistent-claim
  storageSize: 20Gi
  claimDeletePolicy: false
  storageClass: ibmc-file-retain-gold
  userName: my-user
zookeeper:
  replicas: 2
  storageType: persistent-claim
  storageSize: 20Gi
  claimDeletePolicy: false
  storageClass: ibmc-file-retain-gold
 


